name: audit

on:
  push:
    branches: [ "main" ]
    paths: 
      - '**/Cargo.lock'
      - '**/Cargo.toml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - '**/Cargo.lock'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
    - name: Audit
      run: cargo audit
