name: tests

on:
  push:
    branches: [ "main" ]
    paths: 
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**.rs'
  pull_request:
    branches: [ "main" ]
    paths: 
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
